Repository ROCm/rocprofiler-systems, pull requests merged in 2025-04, with the labels that each got.

#145 Network performance profiling how-to
  .wordlist.txt
  CHANGELOG.md
  docs/data/rocprof-sys-perfetto-nic-trace.png
  docs/how-to/nic-profiling.rst
  docs/index.rst
  docs/sphinx/_toc.yml.in
Labels: documentation

#160 Disable AUTOREQ and manually add requirements.
  cmake/ConfigCPack.cmake
  cmake/Packages.cmake
Labels: packaging

#143 Added ctest for NIC performance profiling
  .github/workflows/opensuse.yml
  .github/workflows/redhat.yml
  .github/workflows/ubuntu-focal.yml
  .github/workflows/ubuntu-jammy.yml
  tests/CMakeLists.txt
  tests/rocprof-sys-nic-perf.cmake
Labels: workflow, testing

#164 By default disabling CPU Frequency
  source/lib/core/config.cpp
Labels: bug

#180 Broken link fix to How-to: Configuring Runtime Options [amd-staging]
  docs/how-to/configuring-runtime-options.rst
Labels: documentation

#181 Broken link fix to How-to: Configuring Runtime Options [6.4.0] …
  docs/how-to/configuring-runtime-options.rst
Labels: documentation

#182 Changelog edited to sync with release branch and clarity [amdstaging]
  CHANGELOG.md
Labels: documentation

#178 Fix for AMD_SMI_METRICS collection settings
  CHANGELOG.md
  source/lib/core/config.cpp
  source/lib/rocprof-sys/library/amd_smi.cpp
Labels: bug

#188 Editorial to changelog synced with AMD-staging
  CHANGELOG.md
Labels: documentation
